'use client';
import React, { useEffect } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'swiper/css';
import './globals.css';
import Header from '@/components/common/Header/Header';
import StoreProvider from './StoreProvider';
import AuthModals from '@/components/features/Auth/AuthModals';

import { usePathname } from 'next/navigation';
import DashboardHeader from '@/components/common/dashboard/Header/Header';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let pathName = usePathname();

  // Determine the class name based on the route
  const getBodyClass = () => {
    if (pathName.startsWith('/admin-dashboard')) {
      return 'grid grid-cols-[50px,1fr] min-[450px]:grid-cols-[80px,1fr] lg:grid-cols-[280px,1fr] min-h-screen grid-rows-[70px,1fr,40px] sm:grid-rows-[100px,1fr,60px] transition-all duration-300 overflow-x-hidden';
    }
    return 'default-body';
  };

  // Apply the class name immediately on the client
  useEffect(() => {
    document.body.className = getBodyClass();
  }, [pathName]);

  return (
    <html lang='en'>
      <body className={`${inter.className} ${getBodyClass()}`}>
        <StoreProvider>
          {pathName.startsWith('/admin-dashboard') ? (
            <DashboardHeader />
          ) : (
            <>
              <Header />
              <AuthModals />
            </>
          )}
          {/* <Header /> */}

          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
