import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'swiper/css';
// import 'swiper/components/pagination/pagination.min.css';
// import 'swiper/components/navigation/navigation.min.css';
import './globals.css';
import Header from '@/components/common/Header/Header';
import StoreProvider from './StoreProvider';
import AuthModals from '@/components/features/Auth/AuthModals';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          <AuthModals />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
